### ISSUE TITLE
Message metadata unavailable in intent_script

### ISSUE THREAD

**Issue by bastiaanterhorst** [agileek/hassio-addons#54]
**Describe the bug**
I am using intents to trigger actions when receiving Signal messages. However, I have been unable to use any of the message metadata in these scripts. Looking through the code, it seems that [several things are passed on](https://github.com/agileek/hassio-addons/blob/b25ff0820e6380e0f44f024551afe5a67fe95fcd/signal/root/app/signal_message.py#L5), but I cannot seem to access these variables in my intent_script. I have tried doing so with the following syntax:

```
intent_script:
  Test:
    action:
      - service: script.signal_assistant
        data_template:
          sender: "{{ sender }}"
```

But `sender` remains empty.

Am I incorrect in assuming I can access these variables, am I doing something wrong, or is there a bug somewhere?
